### ISSUE TITLE
the-xpdo-constructor markdown

### ISSUE THREAD

**Issue by tonyklapatch** [modxorg/Docs#7]
## Affected page(s)

http://modxdocs.mhserver.nl/current/en/xpdo/getting-started/fundamentals/xpdo,-the-class/the-xpdo-constructor

## What needs to be improved?

Page does not seem to render properly, renders as raw markdown.

## Relevant versions

The problem affects the following version(s): 

- [x] 2.x (current)
- [x] 3.x

**Comment by Mark-H** [comment]
Hmm, looking at the [raw source](https://raw.githubusercontent.com/Mark-H/Docs/2.x/en/xpdo/getting-started/fundamentals/xpdo%2C-the-class/the-xpdo-constructor.md), I'd say the first code blocks being on the same line as the initial (bolded) text is causing this. The markdown parser sees the (closing) code blocks as the start, so it stops parsing there. 

FYI: As I'm still regularly overwriting the files in this repo in the conversion, we can't go ahead an fix this here just yet, at least not until we did the final import from the current docs site and do a temporary freeze until the markdown-based docs go live. But it's great to start logging issues like this so that when we do get to that, we know what to fix!

**Comment by Mark-H** [comment]
This is fixed
